# Generated by Django 5.2.4 on 2025-11-21 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohesify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, upload_to='cohesify/posts/'),
        ),
    ]
