# Generated by Django 5.2.4 on 2025-11-21 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohesify', '0002_post_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
